services:
  app:
    container_name: beta-pokemon-app
    image: beta-pokemon-app:staging
    build:
      context: .
      dockerfile: Dockerfile.staging
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: staging
      DATABASE_URL: ${DATABASE_URL_STAGING}
